### ISSUE TITLE
action卡在了cd /home/runner/work/roam2github-actions/roam2github-actions这一步。

### ISSUE THREAD

**Issue by secondbrain-note** [JimmyLv/roam2github-actions#2]
Jimmy，你好。我根据这个roam2github的原教程设置了我的github库，复制了你的代码到main.yml，同时也用了你的图片备份的py文件，但是workflow里的action提示以下错误
/home/runner/work/_temp/8936dc21-db74-4940-b356-a3f132e0ad9e.sh: line 6: cd: /home/runner/work/roam2github-actions/roam2github-actions: No such file or directory 错误：进程完成 退出代码为 1。

这个错误对应你的yml原来的代码是cd /home/runner/work/roam2github-actions/roam2github-actions

请问这个问题该怎么解决呢？

**Comment by JimmyLv** [comment]
呀哈，你的仓库名是不是不叫 roam2github-actions 呢？

**Comment by secondbrain-note** [comment]
是的，前几天我意识到这个问题了，没仔细看代码，没有动脑子。谢谢Jimmy的回复。

**Comment by JimmyLv** [comment]
👍

**Comment by JimmyLv** [comment]
👍
